package com.pa.demo.common.entity;
// Generated Dec 23, 2019 10:28:18 AM by Hibernate Tools 5.2.10.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import lombok.Builder;

/**
 * User generated by hbm2java
 */
@Builder
@Entity
@Table(name = "\"user\"", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
public class User implements java.io.Serializable {
  private static final long serialVersionUID = 1L;

  private int userId;
  private String uid;
  private String name;
  private Date updateDate;
  private Date insertDate;

  public User() {}

  public User(int userId, String uid, String name, Date insertDate) {
    this.userId = userId;
    this.uid = uid;
    this.name = name;
    this.insertDate = insertDate;
  }

  public User(int userId, String uid, String name, Date updateDate, Date insertDate) {
    this.userId = userId;
    this.uid = uid;
    this.name = name;
    this.updateDate = updateDate;
    this.insertDate = insertDate;
  }

  @Id

  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "user_id", unique = true, nullable = false)
  public int getUserId() {
    return this.userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  @Column(name = "uid", unique = true, nullable = false)
  public String getUid() {
    return this.uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  @Column(name = "name", nullable = false)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "update_date", length = 29)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "insert_date", nullable = false, length = 29)
  public Date getInsertDate() {
    return this.insertDate;
  }

  public void setInsertDate(Date insertDate) {
    this.insertDate = insertDate;
  }
}
